singleQuote: true
semi: false
printWidth: 100
trailingComma: none
bracketSameLine: true
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
